version: 2
updates:
- package_manager: "javascript"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package_manager: "ruby:bundler"
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
