version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.2
      environment:
      - RAILS_ENV: test
      - BASIC_AUTH_USERNAME: hogehoge
      - BASIC_AUTH_PASSWORD: fugafuga
      - SELENIUM_CHROME_HEADLESS: true
    - image: circleci/postgres:13.4
      environment:
      - POSTGRES_USER: root
      - POSTGRES_PASSWORD: root
      - POSTGRES_DB: gss2019_test
      - POSTGRES_HOST: 127.0.0.1
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
        - v1-dependencies-
    - run:
        name: Install system dependencies
        command: |
          sudo apt-get install fonts-migmix
    - run:
        name: Install Chrome
        command: |
          sudo apt update
          sudo apt install -y libappindicator3-1
          sudo apt install -y libvulkan1 udev libudev1 libu2f-udev libgbm1 libwayland-server0 fonts-liberation libasound2 libnspr4 libnss3 xdg-utils
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb
          /opt/google/chrome/google-chrome --version
    - run:
        # v2.1.4 for Heroku
        name: Install appropriate version's Bundler whose number is written in 'Gemfile.lock'
        command: |
          gem install bundler:2.1.4
    - run:
        # v2.1.4 for Heroku
        name: Install gems written in Gemfile
        command: |
          bundle _2.1.4_ install --jobs=4 --retry=3 --path vendor/bundle
    - run:
        name: Install Yarn
        command: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update
          sudo apt install yarn
    - run:
        name: Execute yarn install
        # TODO: 調整の必要あり
        command: yarn install
    - save_cache:
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
        paths:
          - vendor/bundle
          - node_modules
    - run:
        name: Wait for booting DBMS
        command: dockerize -wait tcp://127.0.0.1:5432 -timeout 10s
    - run:
        # db:migrate の前に実行しておかないと Schemefile の ダブルクォート でコケる
        name: Execute RuboCop
        command: bundle exec rubocop
    - run:
        name: Setup database
        command: bin/rails db:create; bin/rails db:migrate;
    - run:
        name: Run Rails Test
        command: |
          mkdir /tmp/test-results
          bundle exec rspec --format progress \
                          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
        when: always # RuboCopは失敗しても通す（WARNING以上は落としてもいいかもしれない）
