default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('PG_USERNAME') %>
  password: <%= ENV.fetch('PG_PASSWORD') %>
  host: <%= ENV.fetch('PG_HOST') %>
  timeout: 5000

development:
  <<: *default
  database: gss2019_development

test:
  <<: *default
  database: gss2019_test

production:
  <<: *default
  database: gss2019_production
