on: [push]
name: Suikoden Election 2019
jobs:
  eiyuden_chronicle_rewards_github_actions:
    name: Suikoden Election 2019 CI
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.2
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
