on: [push]
name: Suikoden Election 2019
jobs:
  suikoden_election_2019_github_actions:
    name: Suikoden Election 2019 CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.5']
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Ruby のセットアップを行う
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install appropriate version's Bundler
      run: gem install bundler:2.1.4
    - name: $ bundle install
      run: |
        bundle config path vendor/bundle
        bundle _2.1.4_ install --jobs=4 --retry=3
